# Athletes Data

In [73]:
import numpy as np
import pandas as pd

In [74]:
bios = pd.read_csv('bios.csv')

In [75]:
bios.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•Blanchy",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-Atlantiques (FRA)",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiques (FRA)","17 July 1994 in Arbonne, Pyrénées-Atlantiques (FRA)",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN

### What should we clean up?

- [x] Get rid of bullet points in Used Names
- [x] Split height/weight
- [x] Parse out dates from `Born` & `Died` column
- [x] Parse out city, region, and country from `Born` column
- [x] Get rid of extra columns

In [76]:
df = bios.copy()

In [77]:
df['name'] = df['Used name'].str.replace("•", " ")  # we used str for string

In [79]:
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•Blanchy",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-Atlantiques (FRA)",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiques (FRA)","17 July 1994 in Arbonne, Pyrénées-Atlantiques (FRA)",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,Jean Borotra
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,Jacques Brugnon
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Albert Canet

In [80]:
# Split the Measurements column into height & weight columns
df[['height_cm', 'weight_kg']] = df['Measurements'].str.split('/', expand=True)  # expand: make height and weight in different columns

In [81]:
# Remove any non-numeric characters (like "cm", "kg", or spaces) using regex
# \D+ matches one or more non-digit characters and replaces them with nothing
#df['height_cm'] = pd.to_numeric(df['height_cm'].str.replace(r'\D+', '', regex=True), errors='coerce')

# pd.to_numeric converts the cleaned strings into numeric values
# errors='coerce' ensures invalid values are turned into NaN instead of raising errors
df['height_cm'] = pd.to_numeric(df['height_cm'].str.strip(' cm'), errors='coerce')
df['weight_kg'] = pd.to_numeric(df['weight_kg'].str.strip(' kg'), errors='coerce')

In [82]:
df.sort_values('height_cm', ascending=False)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name,height_cm,weight_kg
89070,Competed in Olympic Games • Other,Male,Yao•Ming,Yao•Ming,"12 September 1980 in Xuhui District, Shanghai (CHN)",NaN,People's Republic of China,89782,226 cm / 141 kg,"Shanghai Sharks, Shanghai (CHN) / Houston Rockets, Houston (USA)",NaN,NaN,NaN,NaN,姚•明,Oriental,Yao Ming,226.0,141.0
5781,Competed in Olympic Games,Male,"Thomas Loren ""Tommy""•Burleson",Tommy•Burleson,"24 February 1952 in Crossnore, North Carolina (USA)",NaN,United States,5804,223 cm / 102 kg,"NC State Wolfpack, Raleigh (USA)",NaN,NaN,NaN,NaN,NaN,NaN,Tommy Burleson,223.0,102.0
6978,Competed in Olympic Games,Male,Arvydas Romas•Sabonis,Arvydas•Sabonis,"19 December 1964 in Kaunas, Kaunas (LTU)",NaN,Lithuania Soviet Union,7013,223 cm / 122 kg,"Žalgiris Kaunas, Kaunas (LTU) / Real Madrid, Madrid (ESP) / Portland Trail Blazers, Portland (USA)",Sabas,NaN,"Arvidas Romas Sabonis, Арвидас Ромас Сабонис",Lithuania,NaN,NaN,Arvydas Sabonis,223.0,122.0
89075,Competed in Olympic Games,Male,Roberto•Dueñas Hernández,Roberto•Dueñas,"1 November 1975 in Madrid, Madrid (ESP)",NaN,Spain,89787,221 cm / 137 kg,"FC Barcelona, Barcelona (ESP)",NaN,NaN,NaN,NaN,NaN,NaN,Roberto Dueñas,221.0,137.0
120266,Competed in Olympic Games,Male,Zhang•Zhaoxu,Zhang•Zhaoxu,"18 November 1987 in Binzhou, Shandong (CHN)",NaN,People's Republic of China,122147,221 cm / 110 kg,"Shanghai Sharks, Shanghai (CHN)",NaN,NaN,NaN,NaN,张•兆旭,Oriental,Zhang Zhaoxu,221.0,110.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145490,Competed in Olympic Games,Male,Sin•Ye-Chan,Sin•Ye-Chan,13 June 1995,NaN,Republic of Korea,149217,NaN,NaN,NaN,NaN,Shin Ye-Chan,NaN,신•예찬,Oriental,Sin Ye-Chan,NaN,NaN
145491,Competed in Olympic Games,Male,Matthew•Wepke,Matthew•Wepke,5 December 1989,NaN,Jamaica,149218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Matthew Wepke,NaN,NaN
145492,Competed in Olympic Games,Male,Carlos•García-Ordóñez Montalvo,Carlos•García-Ordóñez,"24 April 1927 in La Habana (Havana), Ciudad de La Habana (CUB)","24 November 2019 in Miami, Florida (USA)",Cuba,149219,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Carlos García-Ordóñez,NaN,NaN
145493,Competed in Olympic Games,Female,Landysh Ilsurovna•Falyakhova,Landysh•Falyakhova,"31 August 1998 in Dva Polya Artash, Respublika Tatarstan (RUS)",NaN,ROC,149220,NaN,"SKIF Nizhny Novgorod, Nizhny Novgorod (RUS)",NaN,NaN,NaN,NaN,Ландыш Ильсуровна•Фаляхова,NaN,Landysh Falyakhova,NaN,NaN
145499,Non-starter • Administrator,Male,"William Berge ""Bill""•Phillips",Bill•Phillips,"15 July 1913 in Dulwich Hill, New South Wales (AUS)","20 October 2003 in Sydney, New South Wales (AUS)",Australia,149814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bill Phillips,NaN,NaN

In [90]:
# Parse out dates from 'Born' and 'Died' columns

# a full date like "12 March 1980" (day + month (d{4})+ year d{4}) or a year
date_pattern = r'(\d+ \w+ \d{4}|\d{4})'

# Extract the date (day, month, year) or year only from the "Born" column
df['born_date'] = df['Born'].str.extract(date_pattern) # 12 December 1886	

# Extract only the 4-digit (d{4}) year from the "Born" column
df['born_year'] = df['Born'].str.extract(r'(\d{4})')  # 1886

# Convert the "born_date" column into a proper datetime format
# format="mixed" allows mixed formats (just year or full date)
# errors='coerce' turns invalid values into NaT (Not a Time)
#df['born_date'] = pd.to_datetime(df['born_date'], format="mixed", errors='coerce')  # example: 2 10 1960

# Do the same extraction for the "Died" column
df['died_date'] = df['Died'].str.extract(date_pattern)

# Convert the "died_date" into proper datetime
df['died_date'] = pd.to_datetime(df['died_date'], format='mixed', errors='coerce') # convert month to number not string

df['died_date'].dt.strftime("%d-%B-%Y")  # put - between day and month and year

    # Preview the updated DataFrame
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Name order,name,height_cm,weight_kg,born_date,born_year,died_date,born_city,born_region,born_country
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•Blanchy",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-Atlantiques (FRA)",France,1,NaN,NaN,...,NaN,Jean-François Blanchy,NaN,NaN,12 December 1886,1886,1960-10-02,Bordeaux,Gironde,FRA
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",...,NaN,Arnaud Boetsch,183.0,76.0,1 April 1969,1969,NaT,Meulan,Yvelines,FRA
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiques (FRA)","17 July 1994 in Arbonne, Pyrénées-Atlantiques (FRA)",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",...,NaN,Jean Borotra,183.0,76.0,13 August 1898,1898,1994-07-17,Biarritz,Pyrénées-Atlantiques,FRA
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",...,NaN,Jacques Brugnon,168.0,64.0,11 May 1895,1895,1978-03-20,Paris VIIIe,Paris,FRA
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",...,NaN,Albert Canet,NaN,NaN,17 April 1878,1878,1930-07-25,Wandsworth,England,GBR

In [88]:
# Get city, region, and country from Born column
location_pattern = r'in ([\w\s()-]+), ([\w\s-]+) \((\w+)\)'
df['Born'].str.extract(location_pattern)

                      0                     1    2
0              Bordeaux               Gironde  FRA
1                Meulan              Yvelines  FRA
2              Biarritz  Pyrénées-Atlantiques  FRA
3           Paris VIIIe                 Paris  FRA
4            Wandsworth               England  GBR
...                 ...                   ...  ...
145495            Serov            Sverdlovsk  RUS
145496  Moskva (Moscow)                Moskva  RUS
145497           Kotlas           Arkhangelsk  RUS
145498            Niort           Deux-Sèvres  FRA
145499     Dulwich Hill       New South Wales  AUS

[145500 rows x 3 columns]

In [ ]:
df[['born_city','born_region','born_country']] = df['Born'].str.extract(location_pattern, expand=True)

In [ ]:
#counts how many athletes were born in each city
import pandas as pd
pd.set_option('display.max_colwidth', None)

df.value_counts('born_city',ascending=False).head(25)

born_city
Budapest                          1378
Moskva (Moscow)                    883
Oslo                               708
Stockholm                          629
Praha (Prague)                     600
Toronto                            579
Wien (Vienna)                      547
Buenos Aires                       538
København (Copenhagen)             523
Sydney                             497
Montréal                           468
Berlin                             467
Ciudad de México (Mexico City)     455
Helsinki                           439
Rio de Janeiro                     433
Amsterdam                          429
Barcelona                          425
Melbourne                          417
New York                           416
Seoul                              405
São Paulo                          393
London                             386
Madrid                             379
Athina (Athens)                    348
Roma                               344
Name: count, dtype: int64

In [62]:
# Remove any unneccessary columns
df.columns

Index(['Roles', 'Sex', 'Full name', 'Used name', 'Born', 'Died', 'NOC',
       'athlete_id', 'Affiliations', 'Nick/petnames', 'Title(s)',
       'Other names', 'Nationality', 'Original name', 'Name order', 'name',
       'height_cm', 'weight_kg', 'born_date', 'born_year', 'died_date',
       'born_city', 'born_region', 'born_country'],
      dtype='object')

In [63]:
columns_to_keep = ['athlete_id', 'name', 'born_date', 'born_city', 'born_region',
                   'born_country', 'NOC', 'height_cm', 'weight_kg', 'died_date']

df_clean = df[columns_to_keep]

In [ ]:
df_clean.to_csv('bios_clean.csv', index=False)

## Result

In [ ]:
results = pd.read_csv('bios_clean.csv')

In [72]:
results.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,12 December 1886,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1 April 1969,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,13 August 1898,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,11 May 1895,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,17 April 1878,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25